### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by fuxlud** [Timac/SwiftLint-x-SwiftPackage#1]
Thanks for working on this! 
Looking forward to moving to SPM entirely. 

Please clarify how to build a package (the finale step of your tutorial). I guess you did not mean building a project, as it does not lint.

**Comment by Timac** [comment]
Hey @fuxlud ,

Sorry but I'm not sure to understand your question. With Xcode, you can create a Swift package, add code, and then build the Swift package. You probably want to have a look at https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode for more information
